### ISSUE TITLE
Potential Getting Started Readmes to take a look at

### ISSUE THREAD

**Issue by lauraGgit** [usdot-jpo-ode/jpo-ode#1]
I crowd sourced a couple of examples of good local development Readme docs if you and to take a look. While I personally prefer to have the getting started on the readme, some repos link to a separate doc from the readme.

https://github.com/18F/micropurchase/blob/develop/docs/local_development.md
https://github.com/18F/tock#getting-started
https://github.com/18F/epa-notice
https://github.com/18F/openFEC#set-up

**Comment by tonychen091** [comment]
@lauraGgit I've started integrating some more of the features into the README on the develop branch as we get more up and running. Let me know if you see any specific features or items that you think would be useful. For the time being, we'll keep the getting started within the readme as long as it doesn't get too long.

**Comment by tonychen091** [comment]
README has been created
