### ISSUE TITLE
ODE Slowdown issues

### ISSUE THREAD

**Issue by kimPerry** [usdot-jpo-ode/jpo-ode#104]
While uploading some of our larger data files through the web interface I have run into issues where the ODE slows to a crawl trying to process all of the records. It doesn’t completely crash, but it will go from running at its “normal” pace to processing one record every few minutes (seen from console output). If I try refreshing the web interface during this slow state I get a timeout error. 

Once when looking into this I was able to find a “GC overhead limit exceeded” exception in one of the log files. I don’t remember which log file this came from unfortunately. We restarted the server at that point to get the ODE working again. 

Attached is a zip file with our testing files and a screenshot of the log file with the GC error. You might be able to reproduce this behavior by uploading all of the files through the website, one after the other.
[bsmFiles.zip](https://github.com/usdot-jpo-ode/jpo-ode/files/1019219/bsmFiles.zip)
![odelogmemory](https://cloud.githubusercontent.com/assets/1120608/26314737/1f3b7c3a-3ecc-11e7-985e-aa76b996b242.PNG)

**Comment by mvs5465** [comment]
Thank you Kim, we are looking into this.

**Comment by mvs5465** [comment]
@kimPerry We just merged a fix for this, please let us know if this helps!

**Comment by tonychen091** [comment]
Received confirmation that the fixed worked, closing the issue
