### ISSUE TITLE
TIM to RSU REST Request not returning successful SNMP bindings

### ISSUE THREAD

**Issue by kimPerry** [usdot-jpo-ode/jpo-ode#115]
I'm trying to send a TIM to the RSU in our office using the TIM REST request with a JSON body.

When I use the the "admin" for the RSU username and "password" for the password it is returning:

{SDW={success: true, message: "Deposit to SDW was successful"}, 192.168.0.145={success: true, message: "SNMP deposit successful. RSU IP = 192.168.0.145, Status Code: 0"}}
 
When “v3user” is used for the username the response is: 
 
{SDW={success: true, message: "Deposit to SDW was successful"}, 192.168.0.145={success: false, message: "SNMP deposit failed for RSU IP 192.168.0.145, error code=5(General variable binding error)"}}

In either case I am not seeing the TIM getting created on the RSU. I am not sure if this could be an issue with my JSON, and I'm also not sure which username is correct.

Thanks!
Kim

**Comment by tonychen091** [comment]
@mvs5465: "Looks like at least the communication to/from the RSU was successful, however sometimes the SNMP daemon will put the error inside of a message body and then still return that with success code 0. We can add some more verbose logging to figure out what’s happening."

**Comment by mvs5465** [comment]
Currently we have hardcoded more verbose logging in the branch [tim_debug](https://github.com/usdot-jpo-ode/jpo-ode/tree/tim_debug). 

We should consider adding a configuration property for more verbose logging.

**Comment by mvs5465** [comment]
Looks like this issue occurs when the message already exists in the RSU. To fix this, must set the message status to 6:
`
snmpset -v3 -u v3user -a MD5 -A password -l authNoPriv 192.168.0.40 RSU-MIB::rsuSRMStatus.3 = 6 
`

**Comment by kimPerry** [comment]
As Matt said, I am able to complete sending a TIM to an RSU now as long as I disable an existing TIM with the same index. This has been resolved, thank you!
