### ISSUE TITLE
Unable to send multiple TIMs to an RSU

### ISSUE THREAD

**Issue by kimPerry** [usdot-jpo-ode/jpo-ode#117]
The TIM unique message id comes from the “index” of the Snmpset commands, which is the “.X” at the end of each flag. For example, rsuSRMPayload.3 would create “activemsg_3.conf” on the RSU, and rsuSRMPayload.4 creates “activemsg_4.conf.” The TIMs we’ve been sending through the ODE seem to default to 3. This is only allowing us to send one TIM to an RSU, because sending a TIM with an index that is the same as an existing TIM on an RSU fails. 

Thank you! 
Kim

**Comment by mvs5465** [comment]
To resolve this issue we need to implement these abilities:
1) Query an RSU to view all current TIMs that are active (including the TIM index set on the RSU)
2) Update the TIM REST call to the ODE to include an index for the TIM.
3) Add a REST call to the ODE for the ability to delete a TIM from an RSU(s).

**Comment by tonychen091** [comment]
This issue has been converted into a user story here https://usdotjpoode.atlassian.net/browse/ODE-400

**Comment by mvs5465** [comment]
Functionality for these features implemented in pull request #119. 
For information on how to delete a TIM see:
https://github.com/usdot-jpo-ode/jpo-ode/wiki/Delete-TIM-on-RSU-test

**Comment by mvs5465** [comment]
For information on how to query an RSU for a list of TIMs see:
https://github.com/usdot-jpo-ode/jpo-ode/wiki/Query-RSU-for-set-TIMs

**Comment by mvs5465** [comment]
The new features have been merged into develop. For how to use see:

- [Delete TIM on RSU](https://github.com/usdot-jpo-ode/jpo-ode/wiki/Delete-TIM-on-RSU-test)
- [Sending TIM to RSU](https://github.com/usdot-jpo-ode/jpo-ode/wiki/Sending-TIM-to-RSU-Test) (updated to contain index in JSON body)
- [Query RSU for set TIMs](https://github.com/usdot-jpo-ode/jpo-ode/wiki/Query-RSU-for-set-TIMs)

**Comment by kimPerry** [comment]
These features have been verified and can be used with pull request [#119](https://github.com/usdot-jpo-ode/jpo-ode/pull/119). This issue has been resolved. Thank you!
