### ISSUE TITLE
Unit test Code coverage

### ISSUE THREAD

**Issue by lauraGgit** [usdot-jpo-ode/jpo-ode#12]
As mentioned by #5, it looks the unit tests are only hitting 3.5% of the code by SonarQube's  account. Within SonarQube it looks like your thresholds are set to 65%. 

A colleague who conducted a manual code review had a similar conclusion.

**Comment by hmusavi** [comment]
You and your colleague are absolutely right. We are pushing code fresh off the oven and deferring the test coverage until after the MVP release. If you recall, we announced in one of our weekly meetings at the beginning of the MVP release cycle that this release will be a "prototype" release. This will not even be an alpha release. That said, we have already started adding test coverage to the code and we will be addressing other "issues" identified by SonarQube gradually. 

Thank you for your review and feedback.

**Comment by lauraGgit** [comment]
In agile practice, development of a feature includes adequate testing to ensure quality. So I apologize for missing you mentioning this earlier and my not pushing this point before. In agile practice, feature testing should occur in conjunction with development, typically in the same sprint. Many teams explicitly stipulate testing as the acceptance criteria for a particular feature/user story. In fact my colleagues argue that a feature should not be closed out until the test coverage is at a pre-defined threshold. They have also mentioned that _viability_ cannot be validated if it is not tested.

**Comment by tonychen091** [comment]
Closing this for now, as we've gotten to 90%+ coverage on the existing code base.
