### ISSUE TITLE
TIM units and conversions

### ISSUE THREAD

**Issue by kimPerry** [usdot-jpo-ode/jpo-ode#147]
I've trying to figure out what units the ODE is expecting from TIMs.

For example, the ODE is validating elevation based on meters (-409.5 to 6143.9) while the standard asks for 10 cm units. Doing this conversion before sending the TIM can put the elevation out of bounds. 

Also the standard specifies lat/longs in .1 microdegrees, should the ODE be responsible for the conversion or should that fall on the user? 

I've attached JSON that I've generated that deposits a TIM to an RSU, the nodeLat and nodeLongs are in .1 microdegrees with deltas that match. 

Thank you!
Kim
[timJson.txt](https://github.com/usdot-jpo-ode/jpo-ode/files/1201699/timJson.txt)

**Comment by mvs5465** [comment]
The ODE now only accepts "real values", instead of J2735 encodable values, as part of pull request #149. For more information on what units to use see our [Github Pages](https://usdot-jpo-ode.github.io) site.
