### ISSUE TITLE
TIM Message Frames

### ISSUE THREAD

**Issue by kimPerry** [usdot-jpo-ode/jpo-ode#171]
We heard from Lear that RSUs are expecting TIMs to come with message frames. Currently TIMs generated from the ODE deposit REST endpoint are encoded as "TravelerInformation" objects, can this be adjusted to include the message frame wrapper as well? 

Thanks!
Kim

**Comment by mvs5465** [comment]
This issue has been resolved as part of pull request #173. TIMs sent to RSUs are now wrapped in a message frame.
