### ISSUE TITLE
Metadata document name recommendation.

### ISSUE THREAD

**Issue by jmcarter9t** [usdot-jpo-ode/jpo-ode#175]
People (I am doing it now) will link to the Metadata_v3.md document.  If you change the version number their link will break.  Could you name the current version Metadata.md (or similar) and just change that file.  These are version controlled.  If you want to keep all copies, then you could just "retire" old versions as the next higher number in the retirement pool.

**Comment by tonychen091** [comment]
This has been addressed, combined to be here https://github.com/usdot-jpo-ode/jpo-ode/blob/develop/docs/metadata_standards.md
