### ISSUE TITLE
Suggestion: Metadata value types.

### ISSUE THREAD

**Issue by jmcarter9t** [usdot-jpo-ode/jpo-ode#179]
In the metadata section, the sanitized element is a boolean; the validSignature is a string with boolean value.  A reason for this inconsistency should be provided if it is needed.  If not, consider standardizing value types.

{
  "schemaVersion": 3,
  "metadata": {
    "schemaVersion":3,
    "recordGeneratedBy": "OBU",
    "recrodGeneratedAt": "2016-08-10T16:35:45.138Z[UTC]", 
    "logFileName": "bsm.uper",
    "payloadType": "us.dot.its.jpo.ode.model.OdeBsmPayload",
    "recordType": "bsmRxRecord",
    "serialId": {
        "streamId": "f9c7635a-7763-4e21-bece-cb1104f143b9",
        "bundleSize": 1,
        "bundleId": 12,
        "recordId": 5,
        "serialNumber": 0
     },
    "odeReceivedAt": "2017-09-26T20:00:08.48Z[UTC]",
    **"sanitized": false,
    "validSignature": "true"**
    }
  },

**Comment by tonychen091** [comment]
Updated - should be boolean values https://github.com/usdot-jpo-ode/jpo-ode/blob/develop/docs/metadata_standards.md
