### ISSUE TITLE
PacketIds are larger than Integer types

### ISSUE THREAD

**Issue by kimPerry** [usdot-jpo-ode/jpo-ode#204]
Hi there, 

When I upload dnMsg files through the ODE I'm seeing PacketIds coming out that are much larger than ints, (hex string "EC9C236B0000000000", converts to decimal 4364682555337299984384). Can the packetId in the J2735TravelerInformationMessage class be changed to a datatype large enough to accommodate? 

Thanks!
Kim

**Comment by hmusavi** [comment]
The received TIMs are working correctly. The value that is coming from the OBU is perfectly valid. `packetID` can be up to 9 bytes long which makes it a 18 character HEX string. Our TIM endpoint does not currently accept a 9 byte HEX and that will be fixed. But the received TIM are represented correctly. For our TIM endpoint, there will be changes introduced to accept 9 byte hex values. These changes will require changes on the TIM builder and your TMC application as well.
