### ISSUE TITLE
Querying RSU from ODE not working

### ISSUE THREAD

**Issue by tonychen091** [usdot-jpo-ode/jpo-ode#207]
Reported by Tony E, the querying call `/tim/query` is not working specifically for the RSU that he has connected at his desk. We've noticed that the command line snmpget call works, but its not through the API. We've also confirmed that the rest of the network connected WyDOT RSUs seem to work, but this one does not.

**Comment by tonychen091** [comment]
We are currently rolling back this issue to a previously working solution while we wait for a response from the hardware manufactures.

**Comment by mvs5465** [comment]
Splitting the new query in half provides us with a fix for this issue, it seems that PDUs that exceed a certain packet size may not be properly received by the RSU SNMP agent. This fix was added as part of PR #215 and is tested and working.
