### ISSUE TITLE
TIMs with ITIS code text not supported

### ISSUE THREAD

**Issue by kimPerry** [usdot-jpo-ode/jpo-ode#238]
WYDOT needs the ability to send TIMs with custom ITIS text. This will at a minimum be done when there aren't ITIS codes that match what comes from WYDOT's TMC. Some text that I've gotten from WYDOT that doesn't seem to match any ITIS codes includes:

Traffic being diverted onto interchange ramps
Traffic being diverted onto shoulder.  Expect delays
Traffic being diverted onto [HIGHWAY]

The ODE currently supports ITIS codes from broadcast TIMs, but not custom text.

Thanks!
Kim

**Comment by hmusavi** [comment]
Added ability to support custom text as well as ITIS codes. 
```
//            If the value is purely an integer number, it will be interpreted as
//            ITIS code.  If it is not an integer, it will be interpreted as a
//            text message. If you intend to send an integral value as a literal
//            integer, prefix the number with a single quote ('), for example,
//            "'98765" will be interpreted as literal 98765. The prefix character
//            will be removed before populating  the TIM message. One may mix ITIS
//            code and text in the  items array.
```
See https://usdotjpoode.atlassian.net/browse/ODE-763 for more details.
