### ISSUE TITLE
PPM Containers Exiting

### ISSUE THREAD

**Issue by kimPerry** [usdot-jpo-ode/jpo-ode#243]
The PPM containers are exiting occasionally.

Today the PPM TIM container exited at 16:35 UTC, and at that same time Zookeeper was throwing "Got user-level KeeperException when processing" messages. 

Attached are the Zookeeper and PPM TIM container logs, and also the results from the "docker inspect" command on the PPM TIM container showing when exactly it started and exited. 

[ppmContainerInspect.txt](https://github.com/usdot-jpo-ode/jpo-ode/files/1980788/ppmContainerInspect.txt)
[ppmContainerLogs.txt](https://github.com/usdot-jpo-ode/jpo-ode/files/1980789/ppmContainerLogs.txt)
[zookeeperContainerLogs.txt](https://github.com/usdot-jpo-ode/jpo-ode/files/1980790/zookeeperContainerLogs.txt)

Thanks!
Kim

**Comment by hmusavi** [comment]
Created issue in PPM module repository: https://github.com/usdot-jpo-ode/jpo-cvdp/issues/11

**Comment by hmusavi** [comment]
ODE-769 attempts to fix this issue.
