### ISSUE TITLE
Docker latest tagging pulling untested version

### ISSUE THREAD

**Issue by kimPerry** [usdot-jpo-ode/jpo-ode#244]
The Docker latest tags are now pulling Ubuntu 18.04 and Java 10. 

Incompatibility issues have been observed in the ODE with Spring applications that use Java 8, as well as the jpo-cvdp module which uses gcc 4.9.

**Comment by hmusavi** [comment]
Will update Dockerfiles to use specific working versions.
ubuntu:18.04
gcc/g++: 7

**Comment by hmusavi** [comment]
This issue was fixed as part of ODE-769 and tested by WYDOT.
