### ISSUE TITLE
Need jpo-ode-private Dependency

### ISSUE THREAD

**Issue by huemoua** [usdot-jpo-ode/jpo-ode#253]
I'm going through the Build Process outlined in the README.md; however, I'm stuck at Step 1 that requires the jpo-ode-private repository.  If I try to clone it, it requests credentials.  Please assist.  Thank you.

**Comment by chrisbratlien** [comment]
Same issue here at Texas A&M Transportation Institute. I created an Atlassian/Bitbucket account in order to download the jpo-ode-private repo. It seems that, even when supplying those Atlassian credentials, it doesn't allow me to clone. Is there another approval process one needs to go through to receive access to that repo? I'm very excited to use this project.

Step 2 - Clone private repository
Clone the source code from the BitBucket repository:

git clone --recurse-submodules https://yourbitbucketusername:yourbitbucketpassword@bitbucket.org/usdot-jpo-ode/jpo-ode-private.git

**Comment by musavih2** [comment]
Chris,

We appreciate you reaching out to us and working with the ODE.  For accessing the private repository, your use of the ODE needs to be in line with research efforts associated with the U.S. DOT ITS JPO Data Program.  Would you please let us know about your ODE use case? If your use case is in line with a US DOT JPO Data Program research, then we can promptly grant you access to that repository. However, if it doesn't, you may still pull from the [open-ode](https://github.com/usdot-jpo-ode/jpo-ode/tree/open-ode) branch of the [usdot-jpo-ode/jpo-ode](https://github.com/usdot-jpo-ode/jpo-ode) repository. This branch provides almost all the same major capabilities of the main branch. There are a few minor features in that branch which your use case most likely will not require. So by letting me know your use case, I can determine if the [open-ode](https://github.com/usdot-jpo-ode/jpo-ode/tree/open-ode) branch could work for you. 

Best regards,
ODE Team

**Comment by chrisbratlien** [comment]
Hi Hamid,

Thanks so much for your response. I wasn't aware of the [open-ode](https://github.com/usdot-jpo-ode/jpo-ode/tree/open-ode) branch. That may be all that I need for now.

I must have stopped prematurely when I read "Building this application requires all repositories." 
from **IV. Getting Started**

My main interest is in the asn1_codec and the JSON -> BSM -> JSON conversion, UPER encoding and decoding. It would be great to write CV/AV apps without having to implement that J2735 standard completely on my own.

Beyond that, I also would like to get a general sense of the system referenced from this article: 

[Wyoming integrates connected vehicle data into its traffic management platform](http://www.traffictechnologytoday.com/news.php?NewsID=89575).

_"WYDOT’s ODE contains an open source decoder for ASN.1, expanding the messages into easily-readable JSON (JavaScript Object Notation) used by the Wyoming TMC and many other TMCs."_

I'm encouraged to hear that the [open-ode](https://github.com/usdot-jpo-ode/jpo-ode/tree/open-ode) branch provides most of the major capabilities. I think I'll see what I can find there first and not worry about the private repo.

Thanks again,
Chris

**Comment by musavih2** [comment]
Hi Chris,

If you only need a generic J2735 encoding/decoding, you can use the [asn1_codec](https://github.com/usdot-jpo-ode/asn1_codec) module. That's a standalone module and you will only need kafka and zookeeper containers to use it. However, the input and output to that module is in XML with embedded ASN.1 XER encoding, not JSON.

Thanks,
Hamid

**Comment by hmusavi** [comment]
Access to private repo granted.
