### ISSUE TITLE
PPM container exited

### ISSUE THREAD

**Issue by kimPerry** [usdot-jpo-ode/jpo-ode#255]
Our PPM container went down today around 18:28:41Z, I grabbed the logs for it and zookeeper at this time and attached them.
![ppmlogs_6-7](https://user-images.githubusercontent.com/1120608/41163753-c1399484-6af6-11e8-82c6-71b7309f333e.PNG)
![zookeeperlogs_6-7](https://user-images.githubusercontent.com/1120608/41163756-c2d35438-6af6-11e8-9f96-2de96f5b9bcb.PNG)

**Comment by hmusavi** [comment]
Created https://usdotjpoode.atlassian.net/browse/ODE-776 to address.

**Comment by payneBrandon** [comment]
At this point in time, we are no longer seeing the issue with the PPM container going down. We are good to close this from our perspective.
