### ISSUE TITLE
TIM UTC Start Date Time 

### ISSUE THREAD

**Issue by kimPerry** [usdot-jpo-ode/jpo-ode#256]
Broadcast TIMs sent to the ODE with a start time in UTC seem to incorrectly convert the MinutesOfTheYear start time that gets sent to RSUs and satellite.

For example:
 
startDateTime: “2018-06-11T16:00:00.000Z” yields a startTime of 232800
 
startDateTime: “2018-06-11T10:00-06:00” yields a startTime of 232440
 
I think 232440 is the correct one based on time calculator websites.

This is not critical because we can keep using local time for now, but it might be nice to have the option of using UTC in the future.

**Comment by henclewood** [comment]
Kim,

Thanks for bringing this to our attention. We will look into this issue and get back to you within 48-hours.

Best regards,

ODE Team

**Comment by henclewood** [comment]
Hi Kim,

We are still looking into this issue and we are hoping to get you some more information by tomorrow.

Thanks

ODE Team

**Comment by kimPerry** [comment]
UTC time is getting calculated as it should be, this has been tested and confirmed with our equipment set to UTC time. This issue can be closed.
