### ISSUE TITLE
Log file parsing error

### ISSUE THREAD

**Issue by musavih2** [usdot-jpo-ode/jpo-ode#258]
This issue was reported by @TonyEnglish over email.
`We are finding a bit of problem with log processing through the ODE.  This is happening with many files, but I would like to focus on the a single file (included).  I have included a sample file with ODE logs (log.txt), original Lear file, and decoded file from the ODE.  We are seeing most lines not getting processed.  We have decoded the file with the Lear tool that has all the records, so I think the originating file is okay. `

**Comment by TonyEnglish** [comment]
This issue has be tested in production and fixes the problem.  Thank you.
