### ISSUE TITLE
TMC Data Logs Needed 

### ISSUE THREAD

**Issue by monkey123** [usdot-jpo-ode/jpo-ode#262]
re:[Tony@neaeraconsulting.com] 

We are working to add the TIMs generated at the TMC to the SDC and finding the message format is not consistent.  We are getting this by subscribing to the BroadcastTIM topic.  How can we best fix this so that we have a consistent TIM messaging to the SDC.  We are seeing differences in the TIM data itself as well as the header.

**Comment by musavih2** [comment]
The BoradcastTIM topic publishes the TIM as it is received/requested in ODE REST end-point. The REST end-point is designed to be user friendly and as easy as possible to submit TIM requests. The format of the REST end-point is not one-to-one with a J2735 TIM. If it were, the user would have to know all the details and idiosyncrasies of J2735 which is what we wanted to avoid. That’s the reason for the difference in format. If we want the actual TIM in J2735 format published to a topic, we’ll need to publish the data after ODE has converted it to a valid TIM (right before sending it to be encoded). The J2735 TIM will then be published to a new topic. This issue will be tracked in Jira under [ODE-787](https://usdotjpoode.atlassian.net/browse/ODE-787)

**Comment by hmusavi** [comment]
This issue has been fixed and included in ODE version 1.0.0 which is currently the official release version in `master` branch.
