### ISSUE TITLE
Different content types for TIMs

### ISSUE THREAD

**Issue by kimPerry** [usdot-jpo-ode/jpo-ode#264]
TIMs have different content options: advisory, workZone, genericSign, speedLimit, exitService. It looks like right now the ODE is only supporting "advisory."

Attached is a TIM sent to the ODE with a content of "speedLimit" as well as the exception seen in the ODE logs. 

Thanks!
Kim 

[tim.txt](https://github.com/usdot-jpo-ode/jpo-ode/files/2389563/tim.txt)
[contentError.txt](https://github.com/usdot-jpo-ode/jpo-ode/files/2389567/contentError.txt)

**Comment by hmusavi** [comment]
This issue has been recorded in Jira ticket ODE-844 and put on ODE backlog for Product Owner prioritization and approval.

**Comment by TonyEnglish** [comment]
Rick has verified this is working correctly
