### ISSUE TITLE
Error: MessageProducer -Error Sending record.org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after  60000 ms.

### ISSUE THREAD

**Issue by sruthivijay** [usdot-jpo-ode/jpo-ode#266]
Hi,
I am able to successfully build,deploy and run the project. But the files which are being uploaded are decoded to produce messages on the webUI. It throws the above error. uploaded files data is getting published to the kafka topic. I followed the same instructions. Please help on the same

**Comment by sruthivijay** [comment]
Hi,
        when i run docker-compose ps i get to see only kafka and zookeeper services up, rest adm and aem modules are not up. It throws below error. Please find the screenshot attached for reference. Please let me know if you need any information more on this.

ERROR: for ppm_tim  Cannot create container for service ppm_tim: b'create .: vol
ume name is too short, names should be at least two alphanumeric characters'

ERROR: for ppm_bsm  Cannot create container for service ppm_bsm: b'create .: vol
ume name is too short, names should be at least two alphanumeric characters'

ERROR: for aem  Cannot create container for service aem: b'create .: volume name
 is too short, names should be at least two alphanumeric characters'

ERROR: for adm  Cannot create container for service adm: b'create .: volume name
 is too short, names should be at least two alphanumeric characters'

ERROR: for ode  Cannot create container for service ode: b'create .: volume name
 is too short, names should be at least two alphanumeric characters'
ERROR: Encountered errors while bringing up the project.
The system cannot find the path specified.

![image](https://user-images.githubusercontent.com/19373735/46592806-b05be700-cae3-11e8-968f-b74bc90206b0.png)

**Comment by hmusavi** [comment]
The error seems to point to `DOCKER_SHARED_VOLUME` environment variable not being set. You can set that (and other environment variables required in `docker-compose.yml`) on the system or populate a `.env` files by copying the sample.env file and setting the variables (un-commenting them) as specified.

**Comment by hmusavi** [comment]
May I ask what organization you are with?

**Comment by sruthivijay** [comment]
Hi,
I gave the below path for my docker shared volume
DOCKER_SHARED_VOLUME= "C:/Users/sruthi.vs/jpo-ode"
But it showed error saying
 error: named volume is used in service but no declaration was found in the volumes section.
so i hardcoded the path directly in docker-compose.yml
  ode:
    build: .
    ports:
      - "8080:8080"
      - "9090:9090"
      - "46753:46753/udp"
      - "46800:46800/udp"
      - "5555:5555/udp"
      - "6666:6666/udp"
    environment:
      DOCKER_HOST_IP: 192.168.25.47
      ZK: 192.168.25.47:2181
      SPRING_CONFIG_LOCATION: /host_share/config/
      ODE_DDS_CAS_USERNAME: ${ODE_DDS_CAS_USERNAME}
      ODE_DDS_CAS_PASSWORD: ${ODE_DDS_CAS_PASSWORD}
      ODE_EXTERNAL_IPV4: ${ODE_EXTERNAL_IPV4}
      ODE_EXTERNAL_IPV6: ${ODE_EXTERNAL_IPV6}
      ODE_SECURITY_SVCS_SIGNATURE_URI: ${ODE_SECURITY_SVCS_SIGNATURE_URI}
      ODE_OUTPUT_SCHEMA_VERSION: ${ODE_OUTPUT_SCHEMA_VERSION}
    depends_on:
      - kafka
    links:
      - kafka
      - zookeeper
    volumes:
      - C:/Users/sruthi.vs/jpo-ode/:/jpo-ode

  adm:
    build: ./asn1_codec
    image: jpoode_acm:latest
    environment:
      DOCKER_HOST_IP: 192.168.25.47
      ACM_CONFIG_FILE: adm.properties
    depends_on:
      - kafka
    links:
      - kafka
    volumes:
      - C:/Users/sruthi.vs/jpo-ode/:/asn1_codec_share

  aem:
    build: ./asn1_codec
    image: jpoode_acm:latest
    environment:
      DOCKER_HOST_IP: 192.168.25.47
      ACM_CONFIG_FILE: aem.properties
    depends_on:
      - kafka
    links:
      - kafka
    volumes:
      - C:/Users/sruthi.vs/jpo-ode/:/asn1_codec_share

  ppm_bsm:
    build: ./jpo-cvdp
    image: jpoode_ppm:latest
    environment:
      DOCKER_HOST_IP: 192.168.25.47
      PPM_CONFIG_FILE: ppmBsm.properties
    volumes:
      - C:/Users/sruthi.vs/jpo-ode/:/ppm_data
    depends_on:
      - kafka

  ppm_tim:
    build: ./jpo-cvdp
    image: jpoode_ppm:latest
    environment:
      DOCKER_HOST_IP: 192.168.25.47
      PPM_CONFIG_FILE: ppmTim.properties
    volumes:
      - C:/Users/sruthi.vs/jpo-ode/:/ppm_data
    depends_on:
      - kafka
It resolved the issue. except ppm_tim and ppm_bsm all other modules like adm,ode,aem,kafka and zoo keeper are up.
But still I can't see the decode messages in the WebUI. In the log it's showing the same error
Error: MessageProducer -Error Sending record.org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
I work for West

**Comment by hmusavi** [comment]
The issue is not with ODE. It is with Kafka configuration and most likely related to the DOCKER_HOST_IP. Note that the IP address may change if you switch from one network to another. Try rebooting your machine; checking the IP address again using ipconfig command to ensure that it has not been changed from what  you have in the docker-compose file; remove all containers and rebuild them using `clean-build-and-deploy.cmd` script. If Zookeeper and Kafka are both UP, you should be able to use the `start-kafka-shell.bat` script to launch two Kafka containers and using `start-console-consumer.sh test` command in one container and `start-console-producer.sh test` command in another container. Now typing anything in the produce console should be received and displayed in the consumer console. If this works, then ODE should also be able to communicate through Kafka. If it doesn't work, then we need figure out what's missing in Kafka settings.

**Comment by sruthivijay** [comment]
Hi,
    Thanks for the reply. I will try the solution. I would like to know what path needs to be given to the docker shared volume variable. Is this path correct C:/Users/sruthi.vs/jpo-ode/. This is the path of my project location. I get error when i give this path. Please suggest.

**Comment by hmusavi** [comment]
You can give it any path you wish. This is simply a directory on the host machine that will be shared with the container. It can be used for exchanging data with the container such as log files or config files.

**Comment by sruthivijay** [comment]
I tried launching containers using start-kafka-shell.bat script. But it fails to run with the below error.
![image](https://user-images.githubusercontent.com/19373735/47197892-c345a580-d386-11e8-81d4-ea5e60b91de7.png)
please find my kafka settings below.
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    build: ./docker/kafka
    ports:
      - "9092:9092"
    environment:
      DOCKER_HOST_IP: 192.168.99.100
      ZK: 192.168.99.100:2181
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLED: "true"
      KAFKA_CLEANUP_POLICY: "delete" # delete old logs
      KAFKA_LOG_RETENTION_HOURS: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
      KAFKA_RETENTION_MS: 7200000    # delete old logs after 2 hours
      KAFKA_SEGMENT_MS:   7200000    # roll segment logs every 2 hours.
                                     # This configuration controls the period of time after
                                     # which Kafka will force the log to roll even if the segment
                                     # file isn't full to ensure that retention can delete or compact old data.
    depends_on:
      - zookeeper
    links:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

**Comment by hmusavi** [comment]
I don't think the name of the kafka image is kafka_kafka:latest. It is probably `jpo-ode_kafka:latest`. Please do a `docker images` command to get a list of docker images.

**Comment by hmusavi** [comment]
This is clearly a Kafka issue. I suggest you follow instructions https://github.com/usdot-jpo-ode/kafka-docker or https://github.com/wurstmeister/kafka-docker independent of ODE and try to get Kafka to work. Once you have kafka wired correctly so you can produce and consume using console containers, you should be able to replicate it on ODE.

**Comment by sruthivijay** [comment]
Hi,
     Yeah thanks.. Actually I'm trying to find what's going wrong. If I run
docker-compose ps. I can see the Kafka and zookeeper services to up. But
still Kafka is not working. So I literally couldn't find what's going
wrong. And kafka docker configuration has a different image name. I'll try
to check again. But I have no clue how to fix this. Tried everything.

**Comment by sruthivijay** [comment]
Hi,
     I was able run kafka successfully. Message producer shows a message saying completed publish to topic.Asn1DecoderInput , but after that nothing is happening and I am not able to see the decoded messages on the WebConsole. can you please help fix this?
![image](https://user-images.githubusercontent.com/19373735/47415821-fc6c8400-d791-11e8-8e0a-b798d113e817.png)

**Comment by sruthivijay** [comment]
Hi,
  Thanks for the inputs. It's working fine.
