### ISSUE TITLE
TIM metadata version 5 having undocumented fields

### ISSUE THREAD

**Issue by vmayorskiy-ac** [usdot-jpo-ode/jpo-ode#268]
We checked some TIM messages we received in October, and there is a "request" structure present in "metadata". The structure is not documented for schema version 5. We believe the version needs to be updated to 6 and documentation to include this addition.

  "request": {
    "ode": {
      "verb": 0,
      "index": 3,
      "version": 2
    },
    "rsus": {
      "rsuTarget": "10.145.12.27",
      "rsuUsername": "xxx",
      "rsuRetries": 3,
      "rsuTimeout": 5000,
      "rsuPassword": "xxx"
    },
    "snmp": {
      "mode": 1,
      "deliverystop": "2019-01-01T00:00:00-06:00",
      "rsuid": "00000083",
      "deliverystart": "2018-01-01T00:00:00-06:00",
      "enable": 1,
      "channel": 178,
      "msgid": 31,
      "interval": 2,
      "status": 4
    }
  },

**Comment by hmusavi** [comment]
Thank you for reaching out. A schema change process will be initiated to identify the new metadata fields.

**Comment by hmusavi** [comment]
This issue has been fixed as part of schemaVersion 6 implementation and included in ODE version 1.0.0 which is currently the official release version in `master` branch.
