### ISSUE TITLE
Strange Pattern in TIM data frequency

### ISSUE THREAD

**Issue by wchupp** [usdot-jpo-ode/jpo-ode#270]
There is a strange pattern in the TIM frequency that WYDOT has in their Oracle database. For most days, TIM records come in pairs separated by a few milliseconds, sometimes with the exact same "odereceivedat" time stamp. The pairs come in at random times, minutes to hours apart, but they are consistently in these pairs. Only one of the messages in each pair gets submitted to the SDC firehose endpoint. This might not be an ODE issue, but it is worth looking into to cover all bases. 
[2018-10-24TimDataWYDOT.xlsx](https://github.com/usdot-jpo-ode/jpo-ode/files/2589790/2018-10-24TimDataWYDOT.xlsx)

**Comment by hmusavi** [comment]
@kimPerry @wchupp @vmayorskiy-al Is this issue resolved? If so, please comment and close the issue. If not resolved, please comment on the status.

**Comment by kimPerry** [comment]
We figured out that WYDOT's TIM table stores broadcast and received TIMs, so it will always have a different count than SDC's which is only getting received TIMs.
