### ISSUE TITLE
Driver Alert files don't have correct data

### ISSUE THREAD

**Issue by kimPerry** [usdot-jpo-ode/jpo-ode#312]
Driver alert files are not getting decoded with the correct data. Received message details all have values of zero, and the record generated at date is the same for each record in a file. 

Attached are the files that we observed this with. 

Thanks!
Kim 

[driverAlert_1548196627_fe80%3A%3A226%3Aadff%3Afe05%3A1911.csv.gz](https://github.com/usdot-jpo-ode/jpo-ode/files/2853381/driverAlert_1548196627_fe80.3A.3A226.3Aadff.3Afe05.3A1911.csv.gz)
[driverAlert_1548196849_fe80%3A%3A226%3Aadff%3Afe05%3A1911.csv.gz](https://github.com/usdot-jpo-ode/jpo-ode/files/2853382/driverAlert_1548196849_fe80.3A.3A226.3Aadff.3Afe05.3A1911.csv.gz)

**Comment by hmusavi** [comment]
Bug is confirmed. Created Jira ticket ODE-1136 to address the bug.

**Comment by kimPerry** [comment]
Incoming data has been verified to have varying metadata for driver alerts, TIMs, and BSMs.
