### ISSUE TITLE
Explain relationship between Travis CI and Sonar Cloud?

### ISSUE THREAD

**Issue by alexsoble** [usdot-jpo-ode/jpo-ode#346]
As a newcomer to this project, I'm a bit confused about the relationship between Sonar Cloud and Travis CI. 

The only role Travis appears to be playing is to kick off static analysis and run the test suite on Sonar Cloud, unless I'm mis-reading `.travis.yml`. 

Suggestion: explain in the README the current relationship between Sonar Cloud and Travis CI in the project setup.

**Comment by mvs5465** [comment]
Hi Alex,

In the travis file you will see this line:
` mvn -e clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar`

This is a maven build statement that runs the jacoco lifecycle goal followed by the sonar lifecycle goal. The quality report is assembled as part of the maven build by jacoco, and then uploaded to SonarCloud by sonar.

There is no relationship here, SonarCloud is just a free service we use to host the code quality reports.

Matt

**Comment by alexsoble** [comment]
@mvs5465 Ah, I see, thank you for the explanation! As you can probably tell, I'm not a Java developer. 

Is this an accurate summary? 

1. Travis handles CI and kicks off Maven builds.
1. Maven runs the test suite.
2. JaCoCo builds the code coverage report.
3. Sonar hosts the code coverage report on the web.

**Comment by mvs5465** [comment]
Yup, that's exactly it.

**Comment by mvs5465** [comment]
This documentation has been added in PR #348.
