### ISSUE TITLE
ODE processing BSM logs and dropping critical data (acceleration)

### ISSUE THREAD

**Issue by TonyEnglish** [usdot-jpo-ode/jpo-ode#355]
[1547983898_xml.txt](https://github.com/usdot-jpo-ode/jpo-ode/files/3388194/1547983898_xml.txt)
[processed_BSM_1547983898.txt](https://github.com/usdot-jpo-ode/jpo-ode/files/3388195/processed_BSM_1547983898.txt)
[prod-dot-sdc-cvpep-wydot-bsm-8-2019-06-28-16-27-44-9d2174ef-27f7-4652-aa28-42b06f362d1c.gz](https://github.com/usdot-jpo-ode/jpo-ode/files/3388196/prod-dot-sdc-cvpep-wydot-bsm-8-2019-06-28-16-27-44-9d2174ef-27f7-4652-aa28-42b06f362d1c.gz)
[rxMsg_1547983898_2620%3A31%3A40e0%3A805%3A%3A1.csv.gz](https://github.com/usdot-jpo-ode/jpo-ode/files/3388197/rxMsg_1547983898_2620.3A31.3A40e0.3A805.3A.3A1.csv.gz)

There is an issue with some of the processed BSM files on the SDC missing required fields in the payload coredata accelSet field. This includes missing accelLong, accelLat, accelVert, and accelYaw fields. Although they appear to not all be missing at one time, but rather only a few missing per line. Here is an example from the processed log attached:

prod-dot-sdc-cvpep-wydot-bsm-8-2019-06-28-16-27-44-9d2174ef-27f7-4652-aa28-42b06f362d1c.gz  Line 19 snippet: "accelSet":{"accelLong":0.38,"accelYaw":0.12}

To see if the missing field issue is due to the original BSM log missing the field too, we ran one of the problem logs, ‘rxMsg_1547983898_2620%3A31%3A40e0%3A805%3A%3A1.csv.gz’, through the event log analyzer tool on a Lear OBU. The output XML shows that the original BSM message actually has all of the accelSet fields present and that the generation of the log does not appear to be an issue. The XML output has been attached to the email as ‘1547983898_xml.txt’.

To see if the issue resided with the ODE processing of the original BSM log, the log was processed through the ODE. The resulting json output shows that the accelSet fields are not all present. This seems to show that the issue with the missing accelSet fields seems to be due to something not processing correctly on the ODE. I have attached the output of the ODE in the file ‘processed_BSM_1547983898.txt’.

In order to resolve this issue, the ODE needs to have the accelSet values always present. (accelLong, accelLat, accelVert, and accelYaw); they should always be present in the log files.

**Comment by hmusavi** [comment]
The ODE behavior works as designed.

In general, any `Unavailable` data element as specified by J2735, is represented by `null` in the internal ODE data schema. According to JSON schema best practices, null values are expected to be dropped from the schema.

According to J2735 spec, Acceleration value of `2001` and VerticalAcceleration value `-127` indicate unavailable and therefore would manifest as missing elements in the ODE output schema.

**Excerpts from SAE-J2735 spec**
```
Acceleration ::= INTEGER (-2000..2001) 
-- LSB units are 0.01 m/s^2 
-- the value 2000 shall be used for values greater than 2000 
-- the value -2000 shall be used for values less than -2000 
-- a value of 2001 shall be used for Unavailable

VerticalAcceleration ::= INTEGER (-127..127) 
-- LSB units of 0.02 G steps over -2.52 to +2.54 G 
-- The value +127 shall be used for ranges >= 2.54 G 
-- The value -126 shall be used for ranges <= 2.52 G 
-- The value -127 shall be used for unavailable
```
