### ISSUE TITLE
Intermittent Kafka Bug

### ISSUE THREAD

**Issue by payneBrandon** [usdot-jpo-ode/jpo-ode#365]
There is an intermittent issue with Kafka topics on start of the ODE. This doesn't happen with every reboot, but on occasion the depositors and topics don't seem to communicate properly. We ran into this issue today where the server was rebooted and the ODE restarted automatically (using the docker-compose.yml "restart:always" tag). The ODE and various modules were shown to be running using the docker-compose ps command, and the ODE was working through various TIMs and showing data in the logs as expected. The oddity was that when submitting files with BSMs (bsmLogDuringEvent file for instance) nothing was ever published to the topic.OdeBsmJson topic. This was resolved by manually running 
`docker-compose down
docker-compose up --build -d`

**Comment by snallamothu** [comment]
Brandon, 
Can you attach the log file when this happens at startup?  I am wondering if there is any exception logged in the logs.
Thanks,
Sudhakar

**Comment by payneBrandon** [comment]
I'll grab a log the next time I see this issue come through. When I was digging through the logs before I wasn't seeing any errors coming across though, data simply wasn't getting published to the Kafka topic.
