### ISSUE TITLE
Port Issues

### ISSUE THREAD

**Issue by ZulaliH** [usdot-jpo-ode/jpo-ode#366]
Hello! Is there a specific port that the ODE should be using in order to receive data streaming in from our RSU devices? 

Thanks!

**Comment by jtbaird** [comment]
Hey there! The port should be 24601. Let me know if that resolves this issue.

**Comment by jtbaird** [comment]
Hey @ZulaliH, we'll get right back to you on this.

**Comment by TonyEnglish** [comment]
@ZulaliH the specific port for an RSU or OBU to stream BSM's to the ODE is by default udp 46800, but can be changed in OdeProperties.java located at /jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/OdeProperties.java.  A more detailed description of this capability is located in the ODE Wiki here: https://github.com/usdot-jpo-ode/jpo-ode/wiki/Receive-BSMs-over-UDP.  Hope this helps!

**Comment by ZulaliH** [comment]
Thank you! It was very helpful :)
