### ISSUE TITLE
RSU Depositor Module

### ISSUE THREAD

**Issue by jtbaird** [usdot-jpo-ode/jpo-ode#369]
## Description
Create a `jpo-ode-rsu-depositor` module to handle the "deposit to RSUs" logic.

## Expected Behavior
Should separate deposits from `Asn1EncodedDataRouter` into it's own module, similar to how `jpo-ode-sdw-depositor` is being handled.

## More Info
See: #368

**Comment by snallamothu** [comment]
Issue was addressed on March 27th and requested TriHydro to integration test it.

**Comment by TonyEnglish** [comment]
Brandon has tested this code and has accepted it.
