### ISSUE TITLE
New TIM Content support

### ISSUE THREAD

**Issue by szumpf** [usdot-jpo-ode/jpo-ode#371]
Currently the ODE only supports the content type of "advisory", we are requesting for support of the ability to generate speedLimit TIMs by adding support for the content type of "speedLimit".

**Comment by TonyEnglish** [comment]
![Issue 264 speedLimit content type](https://user-images.githubusercontent.com/16944610/79014740-c1e2dc80-7b28-11ea-89e5-c2034484c1fc.jpg)
The speedlimit (git issue 264).  It looks like this was implemented in Feb 2019.  The details are in Jira issue ODE-844

**Comment by jtbaird** [comment]
Thanks @TonyEnglish, @szumpf let us know if this resolves your issue.

**Comment by TonyEnglish** [comment]
tested by Rick and operational
