### ISSUE TITLE
Sirius XM  TIM received by satellite records failing with INVALID_DATA_TYPE_ERROR  

### ISSUE THREAD

**Issue by richardlsmith** [usdot-jpo-ode/jpo-ode#373]
We have log files from our Sirius XM OBUs that are failing when decoding by the ODE. Only a specific record type is failing. Records that document a TIM received at the OBU from a satellite are failing with the following error:
INVALID_DATA_TYPE_ERROR  `failed ASN.1 binary decoding of element Ieee1609Dot2Data: bad data. Successfully decoded 1 bytes.`

This error is isolated to the “TIM received by satellite” records, other types of records (BSM, TIM received by RSU) found in these rxMsg log files are all being correctly decoded and processed.
Attached is a rxMsg log file offloaded from a Sirius XM OBU. This log file contains two “TIM received by satellite” records. 

[rxMsg_1586802476_fe80__dcf5_fff_fe6d_2051.bin.gz](https://github.com/usdot-jpo-ode/jpo-ode/files/4519176/rxMsg_1586802476_fe80__dcf5_fff_fe6d_2051.bin.gz)

**Comment by richardlsmith** [comment]
Here is a rxMsg log file from a Lear OBU. This log file contains 174 records of TIMs received at the Lear OBU, the first 135 records are for TIMs received from satellite, the records 136 - 165 are for TIMs received from an RSU. 

Unzipped this file should have the same format as the prior .bin file from the Sirius XM OBU. Lear decided to use .csv suffix on these files, but they are binary files. 
[rxMsg_1582232529053_2620_31_40e0_876_226_adff_fe05_1a61.csv.gz](https://github.com/usdot-jpo-ode/jpo-ode/files/4531516/rxMsg_1582232529053_2620_31_40e0_876_226_adff_fe05_1a61.csv.gz)

**Comment by richardlsmith** [comment]
Here is additional information provided by Tony regarding the decoding of the RxSource field
-----------------------------------------------------------------------------
It seems like we are questioning how the ODE is decoding this field.  The code the ODE is using is here:
https://github.com/usdot-jpo-ode/jpo-ode/blob/master/jpo-ode-core/src/main/java/us/dot/its/jpo/ode/model/RxSource.java

And here is a copy of the implementation in the ODE for the RxSource (the file linked above):


public enum RxSource {

RSU,

SAT, // XM satellite

RV, // for BSM rx

SNMP,// for SRM payload from back-end/ODE

NA, // Not applicable (for example, Distress Notification or Driver Alert 

UNKNOWN

}

This is used by the RxMsgFileParser.java located here:
https://github.com/usdot-jpo-ode/jpo-ode/tree/master/jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/importer/parser

This is the implementation based on the included wydotLogRecords.h file
[wydotLogRecords.txt](https://github.com/usdot-jpo-ode/jpo-ode/files/4531599/wydotLogRecords.txt)
(the .h suffix was changed to .txt to allow upload)

**Comment by TonyEnglish** [comment]
SXM found delta in log, they will update and then we can re-test.  We can re-open if this fails
