### ISSUE TITLE
docker-compose.yml Update Needed

### ISSUE THREAD

**Issue by payneBrandon** [usdot-jpo-ode/jpo-ode#386]
To accommodate the expiration logic and new topic `topic.OdeTIMCertExpirationTimeJson`, this topic should be added to the docker-compose file in the `KAFKA_CREATE_TOPICS` section (line 20).

**Comment by dan-du-car** [comment]
@payneBrandon  Please close this issue if it is tested working. Thank you!

**Comment by payneBrandon** [comment]
The update is the same as what was added to our solution to run, and is working fine in our Dev environment.
