### ISSUE TITLE
Asn1EncodedDataRouter Bug

### ISSUE THREAD

**Issue by payneBrandon** [usdot-jpo-ode/jpo-ode#388]
When the security submodule was updated to include the message-expiry field, the data returned to the Asn1EncodedDataRouter now includes both the signed TIM and the message-expiry wrapped into a single field. On [line 198](https://github.com/usdot-jpo-ode/jpo-ode/blob/7db04e0f62f06ff11899e5f727e78fd260230b7b/jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java#L198) the code is pulling the combined data, and converting to Hex. This incorrect data is then sent off to RSUs and the SDX for dissemination. The code here needs to be changed to convert only the encoded TIM ("message-signed" field coming from security submodule [SignatureController](https://github.com/usdot-jpo-ode/jpo-security-svcs/blob/041a7b4b10d6ea36de1205caa4eeace4382f843a/src/main/java/us/dot/its/jpo/sec/controllers/SignatureController.java#L118)) to Hex to be send out to RSUs and the SDX.

**Comment by jtbaird** [comment]
closed as part of release 1.2.0
