### ISSUE TITLE
Installation Trouble:  Service 'adm' failed to build

### ISSUE THREAD

**Issue by GaneshArvapalli-Noblis** [usdot-jpo-ode/jpo-ode#396]
Hello,

I'm new to Docker and was attempting an installation of the ODE. I got through most of the instructions, but failed on one of the final steps. I am on a Windows 10 machine.

I had just finished transferring the *.properties files into the shared Docker volume. The only deviation I made from the listed instructions was within the config.properties modification. Instead of changing `your.docker.host.ip` to my actual Docker host IP, I used `host.docker.internal`.

When I ran `docker-compose up --build -d` in the jpo-ode cloned repository, I was able to install many dependencies, but could not install the "adm" service. Here is the full output:

```
C:\Users\fakepath\jpo-ode>docker-compose up --build -d
Building ode
Step 1/19 : FROM maven:3.5.4-jdk-8-alpine as builder
 ---> fb4bb0d89941
Step 2/19 : MAINTAINER 583114@bah.com
 ---> Using cache
 ---> 79b3928c949b
Step 3/19 : WORKDIR /home
 ---> Using cache
 ---> 750e830559d6
Step 4/19 : COPY ./pom.xml ./
 ---> Using cache
 ---> 741011d9c77e
Step 5/19 : COPY ./jpo-ode-common/pom.xml ./jpo-ode-common/
 ---> Using cache
 ---> 014b62d07854
Step 6/19 : COPY ./jpo-ode-common/src ./jpo-ode-common/src
 ---> Using cache
 ---> ad8f26102fa3
Step 7/19 : COPY ./jpo-ode-plugins/pom.xml ./jpo-ode-plugins/
 ---> Using cache
 ---> 3524aab66cbd
Step 8/19 : COPY ./jpo-ode-plugins/src ./jpo-ode-plugins/src
 ---> Using cache
 ---> 2449fdf198cc
Step 9/19 : COPY ./jpo-ode-core/pom.xml ./jpo-ode-core/
 ---> Using cache
 ---> ff96ad2205fa
Step 10/19 : COPY ./jpo-ode-core/src ./jpo-ode-core/src/
 ---> Using cache
 ---> 92b64fd0ed0d
Step 11/19 : COPY ./jpo-ode-svcs/pom.xml ./jpo-ode-svcs/
 ---> Using cache
 ---> b9b15f5cfbf5
Step 12/19 : COPY ./jpo-ode-svcs/src ./jpo-ode-svcs/src
 ---> Using cache
 ---> f6934b67bb5f
Step 13/19 : RUN mvn clean package -DskipTests
 ---> Using cache
 ---> 24237138ea50

Step 14/19 : FROM openjdk:8u171-jre-alpine
 ---> 0fe3f0d1ee48
Step 15/19 : WORKDIR /home
 ---> Using cache
 ---> f2dc466b9ea5
Step 16/19 : COPY --from=builder /home/jpo-ode-svcs/src/main/resources/application.properties /home
 ---> Using cache
 ---> b31c9b85bfd5
Step 17/19 : COPY --from=builder /home/jpo-ode-svcs/src/main/resources/logback.xml /home
 ---> Using cache
 ---> d46a9c0d62f6
Step 18/19 : COPY --from=builder /home/jpo-ode-svcs/target/jpo-ode-svcs.jar /home
 ---> Using cache
 ---> f57347dbb501
Step 19/19 : ENTRYPOINT ["java",        "-Djava.rmi.server.hostname=$DOCKER_HOST_IP",   "-Dcom.sun.management.jmxremote.port=9090",     "-Dcom.sun.management.jmxremote.rmi.port=9090",         "-Dcom.sun.management.jmxremote",       "-Dcom.sun.management.jmxremote.local.only=true",       "-Dcom.sun.management.jmxremote.authenticate=false",    "-Dcom.sun.management.jmxremote.ssl=false",     "-Dlogback.configurationFile=/home/logback.xml",        "-jar",         "/home/jpo-ode-svcs.jar"]
 ---> Using cache
 ---> 97e62c075e25

Successfully built 97e62c075e25
Successfully tagged jpoode_ode:latest
Building adm
Step 1/33 : FROM ubuntu:18.04
 ---> 56def654ec22
Step 2/33 : USER root
 ---> Using cache
 ---> af26e6a3eafc
Step 3/33 : WORKDIR /asn1_codec
 ---> Using cache
 ---> fd4f45376c91
Step 4/33 : VOLUME ["/asn1_codec_share"]
 ---> Using cache
 ---> 57c79eed05c9
Step 5/33 : RUN apt-get update && apt-get install -y software-properties-common wget git make gcc-7 g++-7 gcc-7-base && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 100 && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 100
 ---> Using cache
 ---> 8c53f3a68623
Step 6/33 : RUN wget https://cmake.org/files/v3.7/cmake-3.7.2.tar.gz && tar -xvf cmake-3.7.2.tar.gz
 ---> Using cache
 ---> 4d534e7afbd8
Step 7/33 : RUN cd cmake-3.7.2 && ./bootstrap && make && make install && cd /home
 ---> Using cache
 ---> aac7d901e53d
Step 8/33 : RUN apt-get update && apt-get install -y automake libtool
 ---> Using cache
 ---> ca9960906175
Step 9/33 : ADD ./librdkafka /asn1_codec/librdkafka
 ---> Using cache
 ---> 903235e4762e
Step 10/33 : RUN cd /asn1_codec/librdkafka && ln -s /usr/bin/python3 /usr/bin/python && ./configure && make && make install
 ---> Using cache
 ---> b31ac4d1b4cc
Step 11/33 : ADD ./pugixml /asn1_codec/pugixml
 ---> Using cache
 ---> 4ea1d667e5e1
Step 12/33 : RUN cd /asn1_codec/pugixml && mkdir -p build && cd build && cmake .. && make && make install
 ---> Using cache
 ---> 7a615e985bb1
Step 13/33 : ADD ./asn1c /asn1_codec/asn1c
 ---> Using cache
 ---> 28df97ea6d4a
Step 14/33 : RUN cd /asn1_codec/asn1c && aclocal && test -f configure || autoreconf -iv && ./configure && make && make install
 ---> Using cache
 ---> 72cee8819735
Step 15/33 : RUN export LD_LIBRARY_PATH=/usr/local/lib
 ---> Using cache
 ---> 017e069c7f6d
Step 16/33 : ADD ./asn1c_combined /asn1_codec/asn1c_combined
 ---> Using cache
 ---> fe41a62e57ff
Step 17/33 : ADD ./scms-asn1 /asn1_codec/scms-asn1
 ---> Using cache
 ---> 1ecf9ab48a5e
Step 18/33 : RUN cd /asn1_codec/asn1c_combined && bash doIt.sh
 ---> Running in c6671811e4a9
J2735_201603DA.ASN: No such file or directory
Cannot parse "J2735_201603DA.ASN"
sed: can't read converter-example.mk: No such file or directory
make: converter-example.mk: No such file or directory
make: *** No rule to make target 'converter-example.mk'.  Stop.
ERROR: Service 'adm' failed to build : The command '/bin/sh -c cd /asn1_codec/asn1c_combined && bash doIt.sh' returned a non-zero code: 2
```

A coworker of mine also attempted the install independently and ran into the same issue. Any help solving this would be appreciated!

**Comment by TonyEnglish** [comment]
J2735_201603DA.ASN is a licensed file that you can get with your copy of J2735, please put your copy of this file in the location: asn1_codec/asn1c_combined/J2735_201603DA.ASN
This should resolve the problem.

**Comment by GaneshArvapalli-Noblis** [comment]
Hey Tony,

Thank you, that seemed to solve the problem. However, I seem to be encountering a new one. While still in the `docker-compose up --build -d` step, I seem to be having some issues with creating containers for some of the services used. In the summary displayed I see the following:
```Successfully built c465645adfe7
Successfully tagged jpoode_sec:latest
jpo-ode_zookeeper_1 is up-to-date
jpo-ode_sec_1 is up-to-date
Starting jpo-ode_kafka_1 ... done
Starting jpo-ode_rde_bsm_depositor_1 ...
Starting jpo-ode_cvpep_tim_depositor_1 ...
Starting jpo-ode_rde_tim_depositor_1   ...
Starting jpo-ode_cvpep_bsm_depositor_1 ...
Creating jpo-ode_ppm_bsm_1             ... error
Creating jpo-ode_adm_1                 ...
Creating jpo-ode_aem_1                 ...
Creating jpo-ode_ode_1                 ...
Creating jpo-ode_ppm_tim_1             ...
Creating jpo-ode_aem_1                 ... error
ERROR: for jpo-ode_ppm_bsm_1  Cannot create container for service ppm_bsm: create .: volume name is too short, names should be at least two alphanumeric characters

Creating jpo-ode_ode_1                 ... error
Creating jpo-ode_adm_1                 ... error
Starting jpo-ode_rde_bsm_depositor_1   ... done
Starting jpo-ode_cvpep_tim_depositor_1 ... done
Starting jpo-ode_rde_tim_depositor_1   ... done
Starting jpo-ode_cvpep_bsm_depositor_1 ... done
ERROR: for jpo-ode_adm_1  Cannot create container for service adm: create .: volume name is too short, names should be aCreating jpo-ode_ppm_tim_1             ... error

ERROR: for jpo-ode_ppm_tim_1  Cannot create container for service ppm_tim: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for ppm_bsm  Cannot create container for service ppm_bsm: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for aem  Cannot create container for service aem: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for ode  Cannot create container for service ode: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for adm  Cannot create container for service adm: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for ppm_tim  Cannot create container for service ppm_tim: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: Encountered errors while bringing up the project.
```

How would I go about fixing these volume creation errors?

**Comment by TonyEnglish** [comment]
I believe your .env file is not quite right, here is a basic sample that i use to get ODE up and running (does not have creds for SDC or data hub, but that is not needed), my local internal ip is used and this is on windows 10 as well (the layout of the DOCKER_SHARED_VOLUME and DOCKER_SHARED_VOLUME_WINDOWS it this is most relevant to the error you are seeing):
###################################
# JPO ODE Docker Environment File #
###################################
# WARNING! The contents of this file may be sensitive. Take care not to add to source control.
#
# Instructions:
#   Rename this file from `sample.env` to `.env` and Docker will automatically pick up the variables.
#
# Description:
#   This file aggregates all the variables used in docker-compose.yml for ease of use. Variables are
#   prefixed with the format DESTINATION_MESSAGETYPE_ to provide guidance. Some variables are filled
#   out with commonly used values.
#
# Variable usage guide:
#   _ACCESS_KEY_ID : The Amazon Web Services (AWS) bucket access key ID.
#   _SECRET_ACCESS_KEY : The AWS bucket secret access key.
#   _BUCKET_NAME : The name of the destination AWS bucket.
#   _DEPOSIT_KEY : The filename prefix appended to files deposited to the destination bucket (may be a file path).
#   _TOPIC : The name of the Kafka topic to which this depositor will listen.
#   _DESTINATION : (Optional) Depositors will default to Firehose depositing. Uncomment this to override to S3 deposit.
###################################

# (Required) The IP address of Docker host machine which can be found by running "ifconfig"
# Hint: look for "inet addr:" within "eth0" or "en0" for OSX
DOCKER_HOST_IP=172.250.250.30

# (Required) The full path of a directory on the host machine to be shared with docker containers.
# Hint: usually the path to the `jpo-ode` directory.
DOCKER_SHARED_VOLUME=/c/GitHub/jpo-ode
DOCKER_SHARED_VOLUME_WINDOWS=C:

CVPEP_BSM_ACCESS_KEY_ID=
CVPEP_BSM_SECRET_ACCESS_KEY=
CVPEP_BSM_BUCKET_NAME=
CVPEP_BSM_DEPOSIT_KEY="wydot-bsm-"
CVPEP_BSM_TOPIC="topic.OdeBsmJson"
#CVPEP_BSM_DESTINATION=s3


RDE_BSM_ACCESS_KEY_ID=
RDE_BSM_SECRET_ACCESS_KEY=
RDE_BSM_BUCKET_NAME=
RDE_BSM_DEPOSIT_KEY="wydot-filtered-bsm-"
RDE_BSM_TOPIC="topic.FilteredOdeBsmJson"
#RDE_BSM_DESTINATION=s3


CVPEP_TIM_ACCESS_KEY_ID=
CVPEP_TIM_SECRET_ACCESS_KEY=
CVPEP_TIM_BUCKET_NAME=
CVPEP_TIM_DEPOSIT_KEY="wydot-tim-"
CVPEP_TIM_TOPIC="topic.OdeTimJson"
#CVPEP_TIM_DESTINATION=s3


RDE_TIM_ACCESS_KEY_ID=
RDE_TIM_SECRET_ACCESS_KEY=
RDE_TIM_BUCKET_NAME=
RDE_TIM_DEPOSIT_KEY="wydot-filtered-tim-"
RDE_TIM_TOPIC="topic.FilteredOdeTimJson"
#RDE_TIM_DESTINATION=s3


# Miscellaneous optional values

#	The username for authenticating the USDOT Situation Data Warehouse WebSocket server
ODE_DDS_CAS_USERNAME=
#	The password for authenticating the USDOT Situation Data Warehouse WebSocket server
ODE_DDS_CAS_PASSWORD=
#	The IPv4 address of the server running ODE
ODE_EXTERNAL_IPV4=
#	The IPv6 address of the server running ODE
ODE_EXTERNAL_IPV6=

#jpo-security-svcs module properties
SEC_CRYPTO_SERVICE_BASE_URI=
ODE_SECURITY_SVCS_SIGNATURE_URI=

# These are just the file names expected to be found in the 
PPM_BSM_CONFIG_FILE=ppmBsm.properties
PPM_TIM_CONFIG_FILE=ppmTim.properties
PPM_MAP_FILE=I_80.edges

**Comment by GaneshArvapalli-Noblis** [comment]
Replacing the .env file with your sample at least seems to have built the container properly. I can fill in the credentials and variables later. Thanks for the help! I'm closing this issue.
