### ISSUE TITLE
Unrestricted Log File Growth

### ISSUE THREAD

**Issue by payneBrandon** [usdot-jpo-ode/jpo-ode#397]
The ODE is copying over the `logback.xml` file from the `jpo-security-svcs` module to handle logging functionalities. This file, is using a [FileAppender](https://github.com/usdot-jpo-ode/jpo-security-svcs/blob/db1021e61f50955d8d42d2bedbc9f6454103c524/src/main/resources/logback.xml#L5) as part of its logging by default that allows an unrestricted file size. This is causing a problem with disk space consumption as the file was seen to exceed 46GB. 

Note that this issue is related to [Logging Settings #21](https://github.com/usdot-jpo-ode/jpo-s3-deposit/issues/21)

**Comment by dan-du-car** [comment]
This issue can be closed.
