### ISSUE TITLE
Standardized Development Environment

### ISSUE THREAD

**Issue by payneBrandon** [usdot-jpo-ode/jpo-ode#407]
As an ODE developer, I want a standardized development environment. This will include standard development tools such as IDE, as well as standard procedure for running the code and debugging the ODE. 

The current system is lacking a standard environment, as well as debug capabilities. This makes development challenging, and allows issues to slip through.

**Comment by TonyEnglish** [comment]
Reviewed and approved by Dan to merge into dev
