### ISSUE TITLE
ODE SVCS Build Error

### ISSUE THREAD

**Issue by drewjj** [usdot-jpo-ode/jpo-ode#416]
There is a build error caused by a variable name in the 'Asn1DecodeMessageJSON.java' class. It was previously changed to share variables across the class but there was a differently named variable for odeData that was not renamed.

Fix by changing line 176 in 'Asn1DecodeMessageJSON.java' from 'odeTimData' to 'odeData'.

**Comment by dan-du-car** [comment]
Close as the PR is merged
