### ISSUE TITLE
Receive SPAT messages over UDP

### ISSUE THREAD

**Issue by drewjj** [usdot-jpo-ode/jpo-ode#447]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Receive SPaT messages over UDP on port 44910 (with IPv4) and send to the existing ODE SPaT OdeRawEncodedSPATJson topic so that they can be decoded like a normal SPaT message.

### ODE version where this issue was discovered

N/A

### Actual behavior

Functionality does not exist currently.

### Steps to reproduce the actual behavior

1. Do this
1. Then do this...
N/A

### Related work

#403

**Comment by dan-du-car** [comment]
The issue is closed as the PR is merged.
