### ISSUE TITLE
Linking SonarQube to Travis

### ISSUE THREAD

**Issue by lauraGgit** [usdot-jpo-ode/jpo-ode#5]
Here is the documentation around hooking SonarQube to Travis.
https://docs.travis-ci.com/user/sonarqube/

**Comment by lauraGgit** [comment]
As well as a plugin on how to add badges to your README: https://github.com/QualInsight/qualinsight-plugins-sonarqube-badges

**Comment by lauraGgit** [comment]
Looks like this is now in the repo from this commit: https://github.com/usdot-jpo-ode/jpo-ode/commit/c623c2799a430bf72ffd62deb4789b1f66642443

**Comment by lauraGgit** [comment]
Given that the coverage is only at 3.5% it seems like the qualityGate threshold is not set, or accurately updating.

**Comment by tonychen091** [comment]
Updated and its currently working now
