### ISSUE TITLE
Remove DOCKER_SHARED_VOLUME_WINDOWS Environmental Variable

### ISSUE THREAD

**Issue by Michael7371** [usdot-jpo-ode/jpo-ode#517]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ x ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Remove the environmental variable DOCKER_SHARED_VOLUME_WINDOWS as it no longer seems required for Windows users.

### ODE version where this issue was discovered
1.4.0

### Expected behavior
The volume attached to Kafka to be the same volume as the volume used for other services.

### Actual behavior
Volume is different and throws errors if DOCKER_SHARED_VOLUME_WINDOWS is set to "c:".

### Steps to reproduce the actual behavior
When set to "C:" a docker build fails to build when using WSL Ubuntu shell. If building using Powershell either "C:" or an empty field works.

### Related work
https://github.com/usdot-jpo-ode/jpo-ode/pull/515

**Comment by paulbourelly999** [comment]
@Michael7371 Can we close this issue if the fix is merged or is the plan to eventually remove the environment variable entirely?

**Comment by dmccoystephenson** [comment]
Has this been done yet? @Michael7371

**Comment by Michael7371** [comment]
@dmccoystephenson No it has not.

**Comment by drewjj** [comment]
This issue has been resolved with #515
