### ISSUE TITLE
Maven build error

### ISSUE THREAD

**Issue by aferber** [usdot-jpo-ode/jpo-ode#87]
Trying to build using maven I get the attached failure.

Here's my maven -version:

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: /opt/apache-maven-3.3.9
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-24-generic", arch: "amd64", family: "unix"

[install_failure.txt](https://github.com/usdot-jpo-ode/jpo-ode/files/894226/install_failure.txt)

**Comment by mvs5465** [comment]
Hi, it looks like you're missing the J2735 dependency. Have you cloned and built the private repository?

**Comment by mvs5465** [comment]
Marking this as resolved.
