### ISSUE TITLE
TIM Input JSON samples don't work

### ISSUE THREAD

**Issue by tonychen091** [usdot-jpo-ode/jpo-ode#91]
They currently have the incorrect values for crc. Should be a bit string

**Comment by mvs5465** [comment]
CRC is a bit-string of length 16. If its left completely blank, the ODE will assign a CRC of value 0.
So two options:
1. Leave it blank: `"crc": "",`
2. Set it to some combination of sixteen 1s and 0s: `"crc": "1010010000010000",`

**Comment by hmusavi** [comment]
We should leave it blank as default if that works but I believe ODE should accept a string value in Java number representation (i.e. 0xABCD or 0b1010010000010000)

**Comment by mvs5465** [comment]
Also we should make the ODE throw an exception if CRC is invalid. That way we can prevent it from trying to deposit it to the RSUs and SDC, and also return a more informative error message.

**Comment by mvs5465** [comment]
New TIM files have been provided and CRC updates have been merged as part of pull request #157. CRC field now accepts 4-digit hex code OR 16-digit binary code, as documented in the ODE [swagger document](https://usdot-jpo-ode.github.io/).
