### ISSUE TITLE
Cross Origin Requests for hte External URL 

### ISSUE THREAD

**Issue by tonychen091** [usdot-jpo-ode/jpo-ode#96]
I’ve been working on a simple website for sending a TIM to an RSU. I found that the ODE was blocking my website from making the /tim POST and was giving me a “cross origin request blocked” error.

**Comment by mvs5465** [comment]
TODO: Looks like we can fix this using a Spring annotation `@CrossOrigin`, placed on either the controller or the specific request mappings. 

See https://spring.io/blog/2015/06/08/cors-support-in-spring-framework

**Comment by mvs5465** [comment]
Addressed in pull request #98.
